# training settings
nepochs:
  value: 200 # 2000 # 7500
train_size:
  value: 200
batch_size:
  value: 50
chi_frequency:
  desc: How often to calculate chi-score for train and test.
  value: 5
seed:
  value: 2

# training features
lambda_:
  value: 0.1
training_balance:
  desc: How many more times to train discriminator than generator.
  value: 2
true_label_smooth:
  desc: Multiply true labels by this to smooth discriminator's labels.
  value: 0.9

# architecture
lrelu:
  value: 0.308623096408301
dropout:
  value: 0.17212992990721143
latent_dims:
  value: 100
g_layers:
  desc: Number of channels in the hidden layers for the generator.
  value: [25600, 512, 256]
d_layers:
  desc: Number of channels in the hidden layers for the discriminator.
  value: [64, 128, 256]


# Adam parameters
learning_rate:
  value: 0.00033311627536622494
beta_1:
  value: 0.5968270381256018
beta_2:
  value: 0.999
clipnorm:
  value:
global_clipnorm:
  value:
use_ema:
  desc: Use exponential moving average in training, causes issues when re-loading weights.
  value: False # only set to true if not loading weights
ema_momentum:
  value: 0.9
ema_overwrite_frequency:
  desc: How often to overwrite weights with ema.
  value: 1
