wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/scripts/train_dcgan.py
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690454627.16784
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.5
      8:
      - 4
      - 5
